= Overview

A simple LangChain based chatbot that offers two types of interaction


* Simple chatbot directly using `ollama` to run `mistral`
* Simple RAG Chatbot adding Chroma, Hugging Face Embeddings

== Usage
. Install ollama on your machine:
+

[source,sh]
----
curl -fsSL https://ollama.com/install.sh | sh
----
+

NOTE:  If you are running on Mac/Windows, just download from Ollama website: link:https://ollama.com/download/mac[ollama for mac] link:https://ollama.com/download/windows[ollama for windows]

. Download your desired module:
+
[source,sh]
----
ollama download mistral
----

. Create a new virtual environment (or if you are comfortable with it, use an existing environment)
+

[source,sh]
----
python3.11 -m venv venv
source venv/bin/activate
----

. Install the dependencies
+

[source,sh]
----
pip install -r requirements.txt
----

. Run the Chainlit application
+

[source,sh]
----
chainlit run -h src/main.py
----


== Frameworks and Libraries

* LangChain
* Chainlit
* Ollama/Mistral

=== RAG Stack additions

* Chroma
* Hugging Face Embeddings lib

== Acknowledgments and Thanks

* Thanks to the authors of the following examples, libraries, patterns, and tools:
* link:https://github.com/shashankdeshpande/langchain-chatbot[langchain-chatbot]
