settings_data:
    - type: "select"
      id: "model"
      label: "Ollama - Model"
      values:
        - "mistral"
        - "llama2"
      initial_index: 0
    - type: "select"
      id: "chain_name"
      label: "Chains"
      values:
        - "Simple Chatbot"
        - "Sales RAG Chatbot"
      initial_index: 1
    - type: "switch"
      id: "streaming"
      label: "Stream Tokens"
      initial: true
    - type: "slider"
      id: "temperature"
      label: "Ollama - Temperature"
      initial: 1
      min: 0
      max: 2
      step: 0.1

welcome_message: |

  ## Important Notice:
  1. This chatbot is meant for internal use only and signifies an experimental stage of the Chatbot that uses a local Language Model (LLM). 
  2. Interactions with this bot are monitored, so please keep your inputs work-related and avoid sharing private or sensitive data.
  3. This bot is not yet fully developed, and its availability may come and go.

  ---

  ## Bot Information

  1. **Bots and LLMs communicate using words that make sense but may not necessarily be true.** 
  2. At present, the Bot does not have access to any company internal knowledge base.

  ---

  ## Example Prompts for the Bot

  Here are a few examples of prompts you can use with this Bot:

  1. **Network Engineers Concerns in an Insurance Company:** What are some common challenges and concerns that network engineers might face while working in an insurance company?
  2. **Marketing Content Writer Assistance:** You are a marketing content writer, help me modify the following text to make it more attractive for sellers, so they can pitch this information effectively to their customers:

  ---



other_var: "aa"    
